# Generated by Django 5.2 on 2025-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_atribuicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
