# Generated by Django 5.2.dev20241028131012 on 2025-05-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoequipamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='solicitacaoequipamento',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
            preserve_default=False,
        ),
    ]
