# Generated by Django 5.2.dev20241028131012 on 2025-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_remove_solicitacaoequipamento_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoequipamento',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
